// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelRequest():Promise<void>;

export function CheckReady(arg1:string,arg2:string):Promise<main.ReadyResult>;

export function ImageDataURL(arg1:string):Promise<string>;

export function OpenDocs(arg1:string):Promise<void>;

export function OpenText(arg1:string):Promise<string>;

export function Recognize(arg1:main.OCRRequest):Promise<main.OCRResult>;

export function SaveText(arg1:string,arg2:string):Promise<string>;

export function SelectImage():Promise<string>;

export function SelectImages():Promise<Array<string>>;
