// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function CheckReady(arg1, arg2) {
  return window['go']['main']['App']['CheckReady'](arg1, arg2);
}

export function ImageDataURL(arg1) {
  return window['go']['main']['App']['ImageDataURL'](arg1);
}

export function OpenDocs(arg1) {
  return window['go']['main']['App']['OpenDocs'](arg1);
}

export function OpenText(arg1) {
  return window['go']['main']['App']['OpenText'](arg1);
}

export function Recognize(arg1) {
  return window['go']['main']['App']['Recognize'](arg1);
}

export function SaveText(arg1, arg2) {
  return window['go']['main']['App']['SaveText'](arg1, arg2);
}

export function SelectImage() {
  return window['go']['main']['App']['SelectImage']();
}

export function SelectImages() {
  return window['go']['main']['App']['SelectImages']();
}
